//using System;
//using System.Collections.Generic;
//using MongoDB.Bson;
//using WebShine.Core.Abstracts;
//using WebShine.Core.Data;

//namespace WebShine.Core.CodeGenerator {

//	public static class AutoGeneratedElementExtensions {

//		public static IEnumerable<AutoGeneratedElement> Children(this AutoGeneratedElement element, IContext context) {

//		}

//		public static AutoGeneratedElement Parent(this AutoGeneratedElement element, IContext context) {
//			if (element.ParentId == ObjectId.Empty) {
//				// TODO:
//			}
//			IElement parent = context.CacheService.Get<DBElement>(String.Format("{0}.{1}", "site", element.ParentId));
//			if (parent == null) {
//				parent = context.ElementRepository.Read(element.ParentId);
//			}


//		}

//		public static AutoGeneratedElement Parent(this AutoGeneratedElement element) {
//			// TODO: dependency resolver!?
//			throw new NotImplementedException();
//		}
//	}
//}
